name: EML_ex03
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pytorch==1.13.1
  - torchvision==0.14.1
  - torchaudio==0.13.1
  - pytorch-cuda=11.7
  - scipy
  - numpy
  - matplotlib
  - pip
